export const instituteData = [{No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
    {No: 0o1, name: "Harsh", email: "Physics", contact: 80, address: 0o3},
]